export default {
    APP_LOADER: 'APP_LOADER',
    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
    FETCH_SEARCH_MOVIES: 'FETCH_SEARCH_MOVIES',
    FETCH_SEARCH_MOVIES_SUCCESS: 'FETCH_SEARCH_MOVIES_SUCCESS',
};